apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq-uploader
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq-uploader
  template:
    metadata:
      labels:
        app: rabbitmq-uploader
    spec:
      containers:
      - name: rabbitmq-uploader
        image: <your-registry>/rabbitmq-uploader:latest
        env:
        - name: RABBITMQ_HOST
          valueFrom:
            configMapKeyRef:
              name: rabbitmq-config
              key: RABBITMQ_HOST
        - name: RABBITMQ_PORT
          valueFrom:
            configMapKeyRef:
              name: rabbitmq-config
              key: RABBITMQ_PORT
        - name: RABBITMQ_USER
          valueFrom:
            secretKeyRef:
              name: rabbitmq-secret
              key: RABBITMQ_USER
        - name: RABBITMQ_PASSWORD
          valueFrom:
            secretKeyRef:
              name: rabbitmq-secret
              key: RABBITMQ_PASSWORD
